'use strict';

var index = require('../index-8fedf5ab.js');

/* src/components/Tile.svelte generated by Svelte v3.29.7 */

const Tile = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { anchor } = $$props, { image } = $$props, { alt } = $$props;
	if ($$props.anchor === void 0 && $$bindings.anchor && anchor !== void 0) $$bindings.anchor(anchor);
	if ($$props.image === void 0 && $$bindings.image && image !== void 0) $$bindings.image(image);
	if ($$props.alt === void 0 && $$bindings.alt && alt !== void 0) $$bindings.alt(alt);

	return `<div class="${"tile"}"><a href="${"#" + index.escape(anchor)}"><picture><source srcset="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?fm=webp&q=25"}" type="${"image/webp"}" media="${"(min-width: 1600px)"}">
    <source srcset="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?fm=webp&q=25&w=1280&fit=crop"}" type="${"image/webp"}" media="${"(min-width: 1280px)"}">
    <source srcset="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?fm=webp&q=25&w=768&fit=crop"}" type="${"image/webp"}" media="${"(min-width: 768px)"}">
    <source srcset="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?fm=webp&q=25&w=568&fit=crop"}" type="${"image/webp"}" media="${"(min-width: 568px)"}">
    <source srcset="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?fm=webp&q=25&w=320&fit=crop"}" type="${"image/webp"}">
    <img src="${"//j-flower-cake.imgix.net/" + index.escape(image) + "?auto=format&q=25&w=1280&fit=crop"}" sizes="${"35vw"}"${index.add_attribute("alt", alt, 0)}></picture></a>
<div${index.add_attribute("id", anchor, 0)} class="${"caption"}"><a href="${"#/"}" class="${"target-dismiss"}">Close</a>
  <h2 class="${"font-secondary"}">A delicious J Flower Cake 1</h2>
  <p>Made from fresh ingredients and original western and Asian flower cake recipes and designs.</p></div></div>`;
});

module.exports = Tile;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/components/Tile.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGlsZS5qcyIsInNvdXJjZXMiOlsiLi4vLi4vLi4vc3JjL2NvbXBvbmVudHMvVGlsZS5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgZXhwb3J0IGxldCBhbmNob3IsIGltYWdlLCBhbHQ7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cInRpbGVcIj5cbjxhIGhyZWY9XCIje2FuY2hvcn1cIj5cbiAgPHBpY3R1cmU+XG4gICAgPHNvdXJjZSBzcmNzZXQ9XCIvL2otZmxvd2VyLWNha2UuaW1naXgubmV0L3tpbWFnZX0/Zm09d2VicCZxPTI1XCIgdHlwZT1cImltYWdlL3dlYnBcIiBtZWRpYT1cIihtaW4td2lkdGg6IDE2MDBweClcIj5cbiAgICA8c291cmNlIHNyY3NldD1cIi8vai1mbG93ZXItY2FrZS5pbWdpeC5uZXQve2ltYWdlfT9mbT13ZWJwJnE9MjUmdz0xMjgwJmZpdD1jcm9wXCIgdHlwZT1cImltYWdlL3dlYnBcIiBtZWRpYT1cIihtaW4td2lkdGg6IDEyODBweClcIj5cbiAgICA8c291cmNlIHNyY3NldD1cIi8vai1mbG93ZXItY2FrZS5pbWdpeC5uZXQve2ltYWdlfT9mbT13ZWJwJnE9MjUmdz03NjgmZml0PWNyb3BcIiB0eXBlPVwiaW1hZ2Uvd2VicFwiIG1lZGlhPVwiKG1pbi13aWR0aDogNzY4cHgpXCI+XG4gICAgPHNvdXJjZSBzcmNzZXQ9XCIvL2otZmxvd2VyLWNha2UuaW1naXgubmV0L3tpbWFnZX0/Zm09d2VicCZxPTI1Jnc9NTY4JmZpdD1jcm9wXCIgdHlwZT1cImltYWdlL3dlYnBcIiBtZWRpYT1cIihtaW4td2lkdGg6IDU2OHB4KVwiPlxuICAgIDxzb3VyY2Ugc3Jjc2V0PVwiLy9qLWZsb3dlci1jYWtlLmltZ2l4Lm5ldC97aW1hZ2V9P2ZtPXdlYnAmcT0yNSZ3PTMyMCZmaXQ9Y3JvcFwiIHR5cGU9XCJpbWFnZS93ZWJwXCI+XG4gICAgPGltZyBzcmM9XCIvL2otZmxvd2VyLWNha2UuaW1naXgubmV0L3tpbWFnZX0/YXV0bz1mb3JtYXQmcT0yNSZ3PTEyODAmZml0PWNyb3BcIiBzaXplcz1cIjM1dndcIiBhbHQ9XCJ7YWx0fVwiPlxuICA8L3BpY3R1cmU+XG48L2E+XG48ZGl2IGlkPVwie2FuY2hvcn1cIiBjbGFzcz1cImNhcHRpb25cIj5cbiAgPGEgaHJlZj1cIiMvXCIgY2xhc3M9XCJ0YXJnZXQtZGlzbWlzc1wiPkNsb3NlPC9hPlxuICA8aDIgY2xhc3M9XCJmb250LXNlY29uZGFyeVwiPkEgZGVsaWNpb3VzIEogRmxvd2VyIENha2UgMTwvaDI+XG4gIDxwPk1hZGUgZnJvbSBmcmVzaCBpbmdyZWRpZW50cyBhbmQgb3JpZ2luYWwgd2VzdGVybiBhbmQgQXNpYW4gZmxvd2VyIGNha2UgcmVjaXBlcyBhbmQgZGVzaWducy48L3A+XG48L2Rpdj5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxNQUFNLGdCQUFFLEtBQUssZ0JBQUUsR0FBRzs7Ozs7OERBSXBCLE1BQU0sMkVBRThCLEtBQUs7a0VBQ0wsS0FBSztrRUFDTCxLQUFLO2tFQUNMLEtBQUs7a0VBQ0wsS0FBSzs0REFDWCxLQUFLLHdGQUF1RCxHQUFHO2dDQUc5RixNQUFNOzs7Ozs7OyJ9
