'use strict';

var index = require('../index-8fedf5ab.js');

/* src/layouts/Layout.svelte generated by Svelte v3.29.7 */

const Layout = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { templateHtml } = $$props, { settings } = $$props;
	if ($$props.templateHtml === void 0 && $$bindings.templateHtml && templateHtml !== void 0) $$bindings.templateHtml(templateHtml);
	if ($$props.settings === void 0 && $$bindings.settings && settings !== void 0) $$bindings.settings(settings);

	return `${($$result.head += `<link rel="${"preconnect"}" href="${"https://fonts.gstatic.com"}" data-svelte="svelte-ck4gci"><link rel="${"stylesheet"}" href="${"/style.css"}" data-svelte="svelte-ck4gci"><link href="${"https://fonts.googleapis.com/css2?family=Alex+Brush&family=Carter+One&display=swap"}" rel="${"stylesheet"}" data-svelte="svelte-ck4gci">${($$result.title = `<title>J Flower Cake — Buttercream and Korean Bean Paste Flowers</title>`, "")}<meta name="${"description"}" content="${"J Flower Cake — Buttercream and Korean Bean Paste Flowers"}" data-svelte="svelte-ck4gci">`, "")}

<header><h1>J Flower Cake</h1></header>

<main>${templateHtml}</main>

<footer><address><span class="${"font-primary"}">J Flower Cake</span><br>
    Middenmolenlaan 8<br>
    2807 DL Gouda
  </address>
  <dl><dt>KVK reg.</dt><dd>80458998</dd><dt>VAT no.</dt><dd>NL003445086B58</dd></dl>
  <small>© J Flower cake, 2021.</small></footer>`;
});

module.exports = Layout;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/layouts/Layout.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTGF5b3V0LmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi9zcmMvbGF5b3V0cy9MYXlvdXQuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgdGVtcGxhdGVIdG1sLCBzZXR0aW5ncztcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDxsaW5rIHJlbD1cInByZWNvbm5lY3RcIiBocmVmPVwiaHR0cHM6Ly9mb250cy5nc3RhdGljLmNvbVwiPlxuICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cIi9zdHlsZS5jc3NcIiAvPlxuICA8bGluayBocmVmPVwiaHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3MyP2ZhbWlseT1BbGV4K0JydXNoJmZhbWlseT1DYXJ0ZXIrT25lJmRpc3BsYXk9c3dhcFwiIHJlbD1cInN0eWxlc2hlZXRcIj5cbiAgPHRpdGxlPkogRmxvd2VyIENha2Ug4oCUIEJ1dHRlcmNyZWFtIGFuZCBLb3JlYW4gQmVhbiBQYXN0ZSBGbG93ZXJzPC90aXRsZT5cbiAgPG1ldGEgbmFtZT1cImRlc2NyaXB0aW9uXCIgY29udGVudD1cIkogRmxvd2VyIENha2Ug4oCUIEJ1dHRlcmNyZWFtIGFuZCBLb3JlYW4gQmVhbiBQYXN0ZSBGbG93ZXJzXCI+XG48L3N2ZWx0ZTpoZWFkPlxuXG48aGVhZGVyPlxuICA8aDE+SiBGbG93ZXIgQ2FrZTwvaDE+XG48L2hlYWRlcj5cblxuPG1haW4+XG4gIHtAaHRtbCB0ZW1wbGF0ZUh0bWx9XG48L21haW4+XG5cbjxmb290ZXI+XG4gIDxhZGRyZXNzPlxuICAgIDxzcGFuIGNsYXNzPVwiZm9udC1wcmltYXJ5XCI+SiBGbG93ZXIgQ2FrZTwvc3Bhbj48YnIgLz5cbiAgICBNaWRkZW5tb2xlbmxhYW4gODxiciAvPlxuICAgIDI4MDcgREwgR291ZGFcbiAgPC9hZGRyZXNzPlxuICA8ZGw+XG4gICAgPGR0PktWSyByZWcuPC9kdD5cbiAgICA8ZGQ+ODA0NTg5OTg8L2RkPlxuICAgIDxkdD5WQVQgbm8uPC9kdD5cbiAgICA8ZGQ+TkwwMDM0NDUwODZCNTg8L2RkPlxuICA8L2RsPlxuICA8c21hbGw+JmNvcHk7IEogRmxvd2VyIGNha2UsIDIwMjEuPC9zbWFsbD5cbjwvZm9vdGVyPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxZQUFZLGdCQUFFLFFBQVE7Ozs7Ozs7O1FBZ0IxQixZQUFZOzs7Ozs7Ozs7Ozs7In0=
